project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Merhaba :)"


  page-footer:
    left: "&copy; Copyright 2024, Author"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  navbar:
    left:
      - href: yayinlar.qmd
        text: Yayınlar

      - href: dersler.qmd
        text: Ders Materyalleri

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



